version: 0.2
phases:
  install:
    commands:
      - echo "Installing Docker"
      - yum install -y docker
      - service docker start
      - docker --version
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 381491836340.dkr.ecr.ap-south-1.amazonaws.com
      - docker info
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag my-app:latest 381491836340.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-06a719e9e7d7/my-app-repo:latest
      - echo Pushing the Docker image to ECR...
      - docker push 381491836340.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-06a719e9e7d7/my-app-repo:latest

artifacts:
  files:
    - '**/*'


    
